### ISSUE TITLE
PHP 7.3 | 7.4 Support

### ISSUE THREAD

**Issue by mojtabaahn** [liara-cloud/laravel-platform#1]
سلام و وقت بخیر 🎉
امکانش هست بیلد با ورژن های مختلف پی اچ پی هم اضافه بشه؟

**Comment by mhemrg** [comment]
سلام.
مجتبی‌جان، مدتی بود که اعلانات گیت‌هاب رو غیر فعال کرده بودم و متاسفانه تازه این صفحه رو دیدم و
برای همین هم خیلی دیر دارم جواب می‌دم.
خبر خوب این‌که این مورد در دست اقدام هست :)

**Comment by FaridAghili** [comment]
سلام
برنامه‌ای برای پی‌اچ‌پی ۸ دارید؟

**Comment by mhemrg** [comment]
سلام جناب عقیلی،
بله. در برنامه‌مون هست.
مستقلا در #2 دنبالش می‌کنیم.
